name: foodlabel_ai
description: Scan food labels, extract ingredients, assess with AI.
publish_to: "none"
version: 1.1.1+111
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.6
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  file_picker: ^8.0.6
  path_provider: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/nl_BE.json
    - assets/i18n/fr_BE.json
