name: Deploy Backend (manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - id: ver
        run: echo "version=$(tr -d '\n\r' < VERSION)" >> "$GITHUB_OUTPUT"

      - name: Resolve config
        run: |
          echo "REGION=${{ vars.GCP_REGION }}" >> $GITHUB_ENV
          echo "SERVICE_NAME=${{ vars.CLOUD_RUN_SERVICE }}" >> $GITHUB_ENV
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "WIF_PROVIDER=${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}" >> $GITHUB_ENV
          echo "WIF_SA_EMAIL=${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}" >> $GITHUB_ENV
          echo "VERSION=${{ steps.ver.outputs.version }}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Apply defaults
        run: |
          : "${REGION:=europe-west1}"
          : "${SERVICE_NAME:=foodlabel-backend}"
          echo "REGION=$REGION" >> $GITHUB_ENV
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "AR_IMAGE=${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/foodlabel-repo/${SERVICE_NAME}" >> $GITHUB_ENV

      - name: Auth
        if: ${{ env.WIF_PROVIDER != '' && env.WIF_SA_EMAIL != '' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Docker auth
        run: gcloud auth configure-docker "${REGION}-docker.pkg.dev" -q

      - name: Build & Push
        run: |
          docker build -t "${AR_IMAGE}:v${VERSION}" -t "${AR_IMAGE}:sha-${SHORT_SHA}" -f backend/Dockerfile .
          docker push "${AR_IMAGE}:v${VERSION}"
          docker push "${AR_IMAGE}:sha-${SHORT_SHA}"

      - name: Deploy
        run: |
          gcloud run deploy "${SERVICE_NAME}" \
            --region "${REGION}" \
            --image "${AR_IMAGE}:v${VERSION}" \
            --allow-unauthenticated \
            --labels "app=foodlabel,version=${VERSION},commit=${SHORT_SHA}"
