name: Infra Stack (Terraform)

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "foodlabel-ai/infra/stack/**"
  workflow_dispatch:

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      TF_WORKDIR: foodlabel-ai/infra/stack

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF - SHARED)
        if: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER != '' && secrets.GCP_SERVICE_ACCOUNT_EMAIL != '' }}
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Fail if no WIF secrets configured
        if: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER == '' || secrets.GCP_SERVICE_ACCOUNT_EMAIL == '' }}
        run: |
          echo "::error::No valid shared WIF secrets (GCP_WORKLOAD_IDENTITY_PROVIDER & GCP_SERVICE_ACCOUNT_EMAIL) for infra workflow."
          exit 1

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.5

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -upgrade

      - name: Terraform Plan (detect drift)
        id: plan
        working-directory: ${{ env.TF_WORKDIR }}
        shell: bash
        run: |
          set +e
          terraform plan -detailed-exitcode -out=tfplan
          CODE=$?
          echo "exitcode=${CODE}" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Apply if changes
        if: steps.plan.outputs.exitcode == '2'
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform apply -auto-approve tfplan

      - name: No changes
        if: steps.plan.outputs.exitcode != '2'
        run: echo "No infra changes detected — skipping apply."
