name: Infra Stack (Terraform)
on:
  push:
    branches: [main, develop]
    paths: ["foodlabel-ai/infra/stack/**"]
  workflow_dispatch:
jobs:
  plan-apply:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    env: { TF_WORKDIR: foodlabel-ai/infra/stack }
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
        with: { project_id: ${{ secrets.GCP_PROJECT_ID }} }
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.6.5 }
      - name: Init
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform init -upgrade
      - name: Plan
        id: plan
        working-directory: ${{ env.TF_WORKDIR }}
        shell: bash
        run: |
          set +e
          terraform plan -detailed-exitcode -out=tfplan
          echo "exitcode=$?" >> $GITHUB_OUTPUT
          exit 0
      - name: Apply
        if: steps.plan.outputs.exitcode == '2'
        working-directory: ${{ env.TF_WORKDIR }}
        run: terraform apply -auto-approve tfplan
